# Microservice : Claims API Microservice
# Language : ASP.NET Core 2.2
# Date: 08-19-2019
# Author: Ganesh Radhakrishnan (ganrad01@gmail.com)
# 
# Description:
# Build & Deploy the 'claims-api' .NET Core microservice on AKS.
# The container image will be built and pushed to an ACR
#
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
# - azure-pipelines

pool:
  name: AKS-Agent-Pool
  demands:
  - Agent.OS -equals Linux
  - k8s-cli -equals kubectl
  - k8s-pm -equals helm

steps:
# Replace tokens with variable values in XML or JSON configuration files
- task: FileTransform@1
  displayName: Replace values for DB connection string
  name: replace_db_Values
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/' 
    fileType: json
    targetFiles: appsettings.json

- script: "echo 'Starting docker build...'"
  displayName: Build start
  name: echo_build_start

- task: Docker@2
  displayName: Login to ACR
  name: docker_login
  inputs:
    command: login
    containerRegistry: $(acrSvcConnection)

- task: Docker@2
  displayName: Build and Push to ACR
  name: docker_build_push
  inputs:
    command: buildAndPush
    repository: claims-api
    Dockerfile: ./dockerfile

- script: "echo 'Finished docker build...'"
  displayName: Build complete
  name: echo_build_complete
