apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "claims-api.fullname" . }}
  labels:
    app: {{ template "claims-api.name" . }}
    chart: {{ template "claims-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "claims-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "claims-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ConnectionStrings__SqlServerDb
            value: "{{ .Values.sqldb.connectionString }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/claims/healthz
              port: http
            initialDelaySeconds: {{ .Values.checks.livenessInitialDelay }}
            periodSeconds: {{ .Values.checks.livenessProbeDelay }}
          readinessProbe:
            httpGet:
              path: /api/v1/claims/healthz
              port: http
            initialDelaySeconds: {{ .Values.checks.livenessInitialDelay }}
            periodSeconds: {{ .Values.checks.readinessProbeDelay }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
